import type { Metadata } from 'next';
import React from 'react';
import Team from '@/components/Team';

export const metadata: Metadata = {
  title: 'MoGo - Contact',
  description: 'Generated by create next app contact',
  keywords: 'word1, word2',
};
const contactPage = () => {
  return (
    <div>
      <Team />
    </div>
  );
};

export default contactPage;
