import type { Metadata } from 'next';
import React from 'react';
import Blog from '@/components/Blog';

export const metadata: Metadata = {
  title: 'MoGo - Blog',
  description: 'Generated by create next app blog',
  keywords: 'word1, word2',
};
const blogPage = () => {
  return (
    <div>
      <Blog />
    </div>
  );
};

export default blogPage;
