import type { Metadata } from 'next';
import React from 'react';
import About from '@/components/About';

export const metadata: Metadata = {
  title: 'MoGo - About',
  description: 'Generated by create next app about',
  keywords: 'word1, word2',
};

const aboutPage = () => {
  return (
    <div>
      <About />
    </div>
  );
};

export default aboutPage;
