import type { Metadata } from 'next';
import React from 'react';
import Info from '@/components/Info';

export const metadata: Metadata = {
  title: 'MoGo - Service',
  description: 'Generated by create next app service',
  keywords: 'word1, word2',
};
const servicePage = () => {
  return (
    <div className="pt-20">
      <Info />
    </div>
  );
};

export default servicePage;
